resources:
  - name: terraform-repo
    type: git
    source:
      uri: https://github.com/amuwonge99/Concourse_Practical.git
      branch: main

jobs:
  - name: gus-job
    plan:
      - get: terraform-repo
        trigger: true
